### ISSUE TITLE
Szkoda słów..

### ISSUE THREAD

**Issue by Swir** [ramicspa/kodi2#2]
Przykro mi remicspa że są ludzie na tym świecie że zazdrości zrobią wszystko...   Nie podawaj się robisz zajebistą robotę oby tak dalej życzę szybkiego powrotu ! Jeśli  będziesz miał ochotę wbij na forum swirtvteam.tk

**Comment by gumball1** [comment]
Faktycznie szkoda slow aby czyims kosztem reklamowac swoje nedzne forum.

**Comment by Swir** [comment]
nie potrzebuje  reklamować forum :) napisałem tylko jak by chciał rozwinąć temat na forum zawsze jest mile widziany i tyle  czepiasz się jak mały gimbus |:)
