### ISSUE TITLE
nasze - kino

### ISSUE THREAD

**Issue by kopernik1983** [ramicspa/kodi2#5]
witam. czy mozna dodac do wtyczki mozliwosc wpisywania danych logowania? stronka wymaga rejestracji w celu ogladania. pozdrawiam.

**Comment by tomasiek** [comment]
Znalazłem coś takiego: http://swirtvteam.tk/showthread.php?tid=169
Pliczek wygląda na czysty - nie wiem jak działa

**Comment by kopernik1983** [comment]
@tomasiek  dzięki zaraz zobacze czy dziala.

**Comment by tomasiek** [comment]
Jeżeli działa to w sumie Michał może prosto dorzucić gui do hasła i loginu i będzie banglać.

**Comment by kopernik1983** [comment]
no niestety nie dziala. chyba ze brak linkow wynika z samej wtyczki

**Comment by ramicspa** [comment]
Witam, pare dni bylem offline ale juz jestem back. wyglada na to ze dodanie opcji logowania rozwiazuje problem, przetestuje jeszcze wtyczke i pojawi sie update

**Comment by kopernik1983** [comment]
@ramicspa  dzięki wielkie. pozdrawiam.

**Comment by kopernik1983** [comment]
wtyczka dziala az milo. mam jeszcze jedna prosbe jak mozna. generalnie korzystam tu z rozrywki i maly problem zauwarzylem. nie ma podzialu na odcinki. linki ze wwszystkich dostepnych odcinkow sa ze tak powiem w jednej kupie. czy daloby rade cos w tym temacie zdzialac?
