### ISSUE TITLE
ramicspa+ObcyTV=ramalien

### ISSUE THREAD

**Issue by tomasiek** [ramicspa/kodi2#8]
Nie wiem czy wiecie, ale na jednym z for dotyczących kodi (grupa zamknięta) doszło do porozumienia pomiędzy jednym z najlepszych twórców buildów do kodi (jak sam o sobie mówi - nie chce się na razie ujawniać, ale powiem że nie jest nam on Obcy...TV ) a ramicspa, długo to trwało, nieskromnie powiem że uczestniczyłem w negocjacjach. Będzie utworzony nowy build kodi, zawierajacy wszystko co najlepsze z repo ramic oraz wszelkie pomysły z buildu ObcyTV + darmowe listy m3u + epg + inne wodotryski. Build będzie bezpłatny, jendakże po 1.04 h odtwarzania będzie wyskakiwał komunikat o tym że build jest bezpłatny, a usunięcie komunikatu może nastąpić dopiero po wpłacie 0,5 euro na konto. Niestety, wpłata ta nie będzie powodowała że komunikat ten nie będzie się później pojawiał... po prostu zniknie po wpłacie (można paypalem), do czasu następnego oglądania powyżej 1.04 h. Także bajki i krótkie seriale się będzie dało oglądac, telewizję też, natomiast filmy tylko do 1.04 h.
Ponoć w kodzie maczał ręce (klawisze) także Paweł z MM..S.... szykuje się wielki booom na polskiej scenie kodi. 
Jest 400 sztuk buildu do testów, zapisy tutaj - trzeba podać numer karty kredytowej wraz ze zdjęciem jej odwrotu. Ma być także wersja VIP - wtedy trzeba podać skan książeczki zdrowia swojej oraz psa.

**Comment by kashkash18** [comment]
Czy w takim układzie wtyczki Ramica nadal będzie można ściągnąć z jego repo i używać tak jak do tej pory czy Ramic jakiego znamy znika i idzie do obcego

**Comment by tomasiek** [comment]
Będzie tylko u obcego... Jest propozycja utworzenia forku, który byłby
bezpłatny jednakże miałby zablokowane odtwarzanie filmów... Ale
wyszukiwanie itp itd by działało normalne, tylko by nie odtwarzało. Zawsze
coś.... Więcej szczegółów będę znał 2 kwietnia.




01.04.2017 10:38 AM "kashkash18" <notifications@github.com> napisał(a):

**Comment by kashkash18** [comment]
No to kapa. Teraz widać że ludzie robiący builidy dopieli swego.Jesli stanie się jak piszesz to idea bardzo dobrych i do tego darmowych wtyczek Ramica upadła. A szkoda bo gość ma zasady których w tych czasach ludziom brakuje.

**Comment by tomasiek** [comment]
A zwróć uwagę na datę dzisiejszą...

01.04.2017 11:05 AM "kashkash18" <notifications@github.com> napisał(a):

**Comment by kashkash18** [comment]
Oooo Ty kur.a :D Taki stary ze mnie grzyb a tak się dałem zrobić hehehe Brawo Ty :D

**Comment by kopernik1983** [comment]
HAHAHAH  :)

**Comment by rafciu27** [comment]
Dobra nabrałem się 😂

**Comment by tomasiek** [comment]
Cholera... myślałem że nikt się na to nie złapie... a tu złapałem starego wygę...
A na powagę. @kashkash18  ma rację:

> bo gość ma zasady których w tych czasach ludziom brakuje.
I za to w imieniu wszystkich którzy korzystają z wtyczke - dzięki wielkie Michał. I na pochybel obcym :) czy innym Alienom czy MMESom
